### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ohbin-kwon** [sharingBookReview-SERVICE/DIVER_API_DOCS#1]
기존의 코드에서 book의 array, bookmark 기능, review, feed, follow에 대한 기능은 mvp단계에서 아직 추가하지 않으실 생각이신건지, 아니면 mvp단계에서도 fix하고 진행하실것인지 궁금하네요

**Comment by kimseungbin** [comment]
빠진 항목들을 목록화하는게 좋을거같아요.
